# Generated by Django 3.0.6 on 2020-05-11 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Project Name')),
            ],
        ),
        migrations.CreateModel(
            name='ServerProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Provider Name')),
            ],
        ),
        migrations.CreateModel(
            name='ServerDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=200, verbose_name='IP Address')),
                ('linked_domain', models.CharField(max_length=200, verbose_name='Linked Domain')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servers.Project')),
            ],
        ),
    ]
