# Generated by Django 3.0.6 on 2020-05-14 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverdetails',
            name='admin_server_url',
            field=models.URLField(null=True, verbose_name='Admin Server URL'),
        ),
        migrations.AddField(
            model_name='serverdetails',
            name='comments',
            field=models.TextField(null=True, verbose_name='Comments'),
        ),
        migrations.AddField(
            model_name='serverdetails',
            name='environment_type',
            field=models.CharField(choices=[('D', 'Development'), ('S', 'Staging'), ('P', 'Production'), ('T', 'Training'), ('M', 'Demo')], max_length=1, null=True, verbose_name='Environment'),
        ),
        migrations.AddField(
            model_name='serverdetails',
            name='expires_on',
            field=models.DateField(null=True, verbose_name='Expires on'),
        ),
        migrations.AddField(
            model_name='serverdetails',
            name='monthly_mount',
            field=models.PositiveIntegerField(null=True, verbose_name='Monthly Amount'),
        ),
        migrations.AddField(
            model_name='serverdetails',
            name='separate_bill',
            field=models.BooleanField(default=False, verbose_name='Separate bill?'),
        ),
        migrations.AddField(
            model_name='serverdetails',
            name='seperate_bill_file',
            field=models.FileField(null=True, upload_to='', verbose_name='Bill file'),
        ),
        migrations.AlterField(
            model_name='serverdetails',
            name='ip_address',
            field=models.GenericIPAddressField(null=True, verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='serverdetails',
            name='linked_domain',
            field=models.CharField(max_length=200, null=True, verbose_name='Linked Domain'),
        ),
    ]
