# Generated by Django 3.0.6 on 2020-05-14 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_auto_20200514_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverdetails',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='servers.ServerProvider'),
        ),
        migrations.AlterField(
            model_name='serverdetails',
            name='admin_server_url',
            field=models.URLField(blank=True, null=True, verbose_name='Admin Server URL'),
        ),
        migrations.AlterField(
            model_name='serverdetails',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='serverdetails',
            name='environment_type',
            field=models.CharField(choices=[('D', 'Development'), ('S', 'Staging'), ('P', 'Production'), ('T', 'Training'), ('M', 'Demo')], max_length=1, verbose_name='Environment'),
        ),
        migrations.AlterField(
            model_name='serverdetails',
            name='expires_on',
            field=models.DateField(blank=True, null=True, verbose_name='Expires on'),
        ),
        migrations.AlterField(
            model_name='serverdetails',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='serverdetails',
            name='linked_domain',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Linked Domain'),
        ),
        migrations.AlterField(
            model_name='serverdetails',
            name='monthly_mount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Monthly Amount'),
        ),
        migrations.AlterField(
            model_name='serverdetails',
            name='separate_bill',
            field=models.BooleanField(blank=True, default=False, verbose_name='Separate bill?'),
        ),
        migrations.AlterField(
            model_name='serverdetails',
            name='seperate_bill_file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Bill file'),
        ),
    ]
