# Generated by Django 3.0.6 on 2020-05-15 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0004_auto_20200514_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='Type')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
        ),
        migrations.AlterField(
            model_name='serverdetails',
            name='separate_bill',
            field=models.BooleanField(blank=True, default=False, verbose_name='Separate Bill?'),
        ),
        migrations.AddField(
            model_name='serverdetails',
            name='payment_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='servers.PaymentType'),
        ),
    ]
